---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  default_configs:
    inherit_from: ".rubocop_todo.yml"
".travis.yml":
  global_env:
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  simplecov: true
  branches:
  - release
  use_litmus: true
  litmus:
    provision_list:
    - ---travis_el
    - travis_deb
    - travis_el7
    - travis_el8
    complex:
    - collection:
        puppet_collection:
        - puppet6
        provision_list:
        - travis_ub_6
    - collection:
        puppet_collection:
        - puppet5
        provision_list:
        - travis_ub_5
  notifications:
    slack:
      secure: A6h/CuKh9x1tYbifGg04I1Dr6Z6E7xCJjMWAj4XVvdXvooAcgQ+A8pZMCFcl9c7URkIj36XS8uzTTzq5Z+ZYiwyLVMJxkSYaRwl2PPxTb/XA3r2f8bxm++XMoMYecUJhy0WkVmEjNarpzHnSi3OWQq6Eup+dEpntJaHFlZptsM0=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  simplecov: true
  use_litmus: true
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
Gemfile:
  optional:
    ":development":
    - gem: ruby-pwsh
    - gem: github_changelog_generator
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
